routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','FycController@index');
Route::get('/offers', 'FycController@getOffers');
Route::get('/products/{slug}','FycController@getProducts');
// Route::get('/{slug}','FycController@getProducts');


Route::post('/sendEmail', 'Auth\ForgotPasswordController@sendEmail')->name('password.emails');
Route::get('/reset-password/{id}', 'Auth\ResetPasswordController@getResetPassword')->name('password.reset');
Route::post('/reset-password', 'Auth\ResetPasswordController@postResetPassword')->name('password.updates');

Route::get('/', 'FycController@index')->name('home');
Route::get('/about', 'FycController@getAbout');
Route::get('/sell-on-homeglare', 'FycController@getSeller');
Route::post('/offer-detail', 'FycController@getOfferDetail');
Route::get('/cart/{id}', 'FycController@getCart');
Route::get('/checkout/{id}', 'FycController@getCheckout');
Route::get('/contact', 'FycController@getContact');
Route::post('/contact',  'SiteController@contactUs');
Route::get('/faq', 'FycController@getFaq');
Route::get('/account/{id}', 'FycController@getAccount');
Route::get('/product-detail/{slug}', 'FycController@getProductDetails');
// Route::get('/product/{slug}', 'FycController@getProducts');
// Route::get('/register', 'FycController@getRegister');
Route::get('/wishlist/{id}', 'FycController@getWishlist');

Route::post('pay', 'PayController@pay');
Route::get('payment-success', 'PayController@success');

Route::get('/auth/redirect/facebook', 'SocialController@redirect');
Route::get('/callback/facebook', 'SocialController@callback');

Route::get('/redirect/google', 'SocialAuthGoogleController@redirect');
Route::get('/callback/google', 'SocialAuthGoogleController@callback');

Route::post('/add-to-cart','AjaxController@addToCart');
Route::post('/add-to-wishlist','AjaxController@addToWishlist');
Route::post('/delete-wishlist-item','AjaxController@deleteWishlistItem');
Route::post('/newsletter', 'SiteController@createNewsletter')->name('newsletter');
Route::post('/cart/delete-product/{id}','AjaxController@deleteSessionData');
Route::post('/update-cart','AjaxController@updateCart');

Auth::routes();

// Route::get('/home', 'FycController@getHome');
// Route::get('/', 'FycController@getHome');
Route::post('/login', 'Auth\LoginController@postLogin');
Route::post('/update-password', 'AjaxController@updatePassword');
Route::post('/update-profile', 'AjaxController@updateProfile');

Route::post('/order-product', 'SiteController@orderProduct')->name('order-product');
Route::get('/order-booked', function()
{
  return view('fyc-web.ordersuccess');
});

// Route::get('/about-us','SiteController@getAboutUs');
// Route::get('/contact','SiteController@getContactUs');
// Route::post('/contact-us', 'SiteController@contactUs')->name('contact-us');
Route::get('/faq','SiteController@getFaq')->name('faq');
Route::get('/terms&conditions','SiteController@getTermsandCondition');
Route::get('/privacy-policy','SiteController@getPrivacyPolicy');
Route::get('/return-policy','SiteController@getReturnPolicy');
Route::get('/my-account/{id}','SiteController@getMyAccount');
Route::get('/ordered-item-details/{order_id}', 'SiteController@orderedItemDetails')->name('ordered-item-details');
Route::get('/ordered-item-track/{order_id}', 'SiteController@orderedItemTrack')->name('ordered-item-track');
Route::resource('reply', 'ReplyController');

Route::get('/show-minicart','AjaxController@showMiniCart');
Route::get('/search-product/productsCat','AjaxController@showProductCat');
Route::get('/search-product/sort', 'AjaxController@sorting');
Route::get('/search-product/price-filter', 'AjaxController@price');
Route::get('/search-product/colored', 'AjaxController@colored');
Route::get('/search-product/rating', 'AjaxController@rating');
Route::resource('help-support', 'HelpSupportController');

Route::get('/get-product_details-data/{productId}', 'AjaxController@getProductDetailsData');
Route::post('/give-product-rating', 'SiteController@giveProductRating')->name('give-product-rating');
Route::post('/global-search-product', 'SiteController@globalSearchProduct')->name('global-search-product');

// snapSocialShare
Route::get('/shareLinkOnSocialSite/{siteKey}/{slug_url}/{product_id}', 'SiteController@shareLinkOnSocialSite');
//fb snap Social Share callback
Route::get('SharedLink/callback/{siteKey}', 'SiteController@SharedLinkCallback');

resources/views/fyc-web/about-us.blade.php
@extends('layouts.fyc')

@section('content')

 <!-- <div class="breadcrumb-area bg-img" style="background-image:url('/fyc-new/images/bg/breadcrumb.jpg);">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <h2>About us page</h2>
                    <ul>
                        <li>
                            <a href="/homew">Home</a>
                        </li>
                        <li class="active">About us </li>
                    </ul>
                </div>
            </div>
        </div> -->
        <div class="about-us-area pt-90 pb-90">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="about-us-img text-center">
                            <a href="#">
                                <img src="{{url('/fyc/beauty.jpg')}}" alt ="">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 align-self-center">
                        <div class="about-us-content">
                            <h2>Welcome To <span>FYC</span> Professionals !</h2>
                            <p>We are here to nurture and nourish the original beauty of individuals with nature.</p>
                            <br>
 <h2>History</h2>
                            <p>In Initial days of brand conceptualization, the biggest question for us was the right market place from which we can reach out important consumers. Well there were lot of potential ways to do it but we found professional beauty industry as the best fit to our research driven, very carefully crafted portfolio of skin therapy.
</p>
<p>
Our Skin Care company was established by Mr NeerajAggrawal and Mrs Neha aggrawal in 2005. Yavi Cosmetics is India’s leading natural cosmetics company. Combining ancient wisdom from the Vedas with 21st century technology, we offer a range of over 200 skin care products for the retail and professional markets. Yavi Cosmetics is more of a sensibly premium, professional skin care range of products. As Our clients demands something close to 100% natural and something which is much more potent that the standard cosmetic regime. Under our brand “FYC” we have a large number of products for professional skin care and routine beauty care products.</p>
                            

                            <br>


<h2>Principles</h2>
<p>The Company works on the principle of :</p>
<ul>
    
<li>• Using only the purest natural extracts and active ingredients in our products.</li>
<li>• Maintaining a high level of quality control and continuous R & D.</li>
<li>• To create a customer friendly transparent policy.</li>
<li>• To offer value for money to our customer.</li>
<li>• To impart training to our employees for continuously improving their performance in respective fields by ensuring total involvement.</li>
</ul>


                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row section-text" >
            <div class="col-sm-4">
                <h4>Eminence Mission</h4>
<p>Yavi Cosmetics with its devotion to perfection and innovation, goes into the creation of a steady stream of products with outstanding functions and superb textures. We are committed to ENHANCE YOUR WELL-BEING NATURALLY through most effective skin care products and extraordinary service.</p>
            </div>
            <div class="col-sm-4">
                <h4>Products Quality</h4>
<p>Yavi Cosmetics focuses on modernity the development of its products is based on “High-Tech” advanced active cosmetology, based on natural ingredients and special technique, which offer effective and visible results. All the products are bio-compatible (i.e. formulated with substances equivalent to the skin). The quality of products is managed by best professionals mainly from cosmetic and herbal industry with collective experience of more than 20 years.</p>
            </div>
            <div class="col-sm-4">
                <h4>Numbers In 2017</h4>
<p>Since 2005, we are developing our company by stepping up investment in markets with outstandng growth in many states all over India. We started with just a couple of products in 5 cities, small distribution network and handful of salons. Yavi Cosmetics today has a large number of quality products, 50 team members, 65 distributors, 5000 salons &lacs of customers all over India. We want to keep on inspiring them all and become a brand that they truly love and trust.</p>
            </div>
        </div>

       <!--  <div class="team-area pt-60 pb-60">
            <div class="container">
                <div class="section-title-2 text-center">
                    <h2>Team Members</h2>
                    <img src="{{url('/fyc-new/images/icon-img/title-shape.png')}} " alt="icon-img">
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <a href="#">
                                    <img src="{{url('/fyc-new/images/team/team-1.jpg')}}" alt=""> 
                                </a>
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="ti-instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Mr.Mike Banding</h4>
                                <span>Manager </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <a href="#">
                                    <img src="{{url('/fyc-new/images/team/team-2.jpg')}}" alt=""> 
                                </a>
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="ti-instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Mr.Peter Pan</h4>
                                <span>Developer </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <a href="#">
                                    <img src="{{url('/fyc-new/images/team/team-3.jpg')}}" alt=""> 
                                </a>
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="ti-instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Ms.Sophia</h4>
                                <span>Designer </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <a href="#">
                                    <img src="{{url('/fyc-new/images/team/team-4.jpg')}}" alt=""> 
                                </a>
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="ti-instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Mr.John Lee</h4>
                                <span>Chairmen </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
         -->
  


        @endsection

resources/views/fyc-web/cart.blade.php
<?php
use App\Models\Product;
use App\Review;
$bill = 0;
$i=0;
$cnt = 0;
?>

@extends('layouts.fyc')

@section('content')

<div class="cart-main-area pt-85 pb-90">
    <div class="container-fluid">
        <h3 class="cart-page-title">Your cart items</h3>
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-9">
                <form action="#">
                    @if(session()->get('cart') != null)

                    <?php

                    $ids = array();
                    $cat_id = array();
                    $quantities = array();


                    foreach(session()->get('cart') as $data)
                    {
                        $ids[$i] = $data->product_id;
                        $quantities[$i] = $data->quantity;
                        $i++;
                    }
                    ?>
                    <div class="table-content table-responsive cart-table-content">
                        <table>
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Until Price</th>
                                    <th>Qty</th>
                                    <th>Subtotal</th>
                                    <th>action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for($j=0 ; $j<$i ; $j++ )
                                <?php
                                $cnt++;
                                $product = Product::where('id',$ids[$j])->first();
                                if($product != null)
                                {
                                    $cat_id[$j] = $product->category_id;
                                }
                                else
                                {
                                    $cat_id[$j] = 0;
                                }
                                ?>
                                <tr id="cart{{$ids[$j]}}">
                                    <td class="product-thumbnail">
                                        <a href="/product-detail/{{$product->slug}}"><img src="{{url('/')}}/{{$product->image1}}" alt="" style="width: 120px; height: 120px"></a>
                                    </td>
                                    <td class="product-name"><a href="/product-detail/{{$product->slug}}">{{strtoupper($product->name)}}</a></td>
                                    <td class="product-price-cart"><span class="amount">₹{{$product->sell_price}}.00</span></td>
                                    <td class="product-quantity">
                                        <div class="">


                                            <i class="ti-minus" style="border: 1px solid #afafaf; padding: 5px 5px 8px; cursor: pointer;" onclick="decrement({{$product->id}})"></i>

                                            <input style="width: 50px; text-align: center;" type="text" name="quantity" id="quantity{{$product->id}}" value="{{$quantities[$j]}}" disabled="disabled ">

                                            <i class="ti-plus" style="border: 1px solid #afafaf; padding: 5px 5px 7px; cursor: pointer;"  onclick="increment({{$product->id}})"></i>

                                        </div>
                                    </td>
                                    <?php
                                    $total = $quantities[$j]*$product->sell_price;
                                    $bill =$bill +  $total;
                                    ?>
                                    <td class="product-subtotal" id="amount{{$product->id}}">₹{{$total}}.00</td>
                                    <td class="product-remove">
                                        <a onclick="deleteCartProduct({{$ids[$j]}})"><i class="la la-close"></i></a>
                                    </td>
                                </tr>
                                @endfor
                            </tbody>
                        </table>
                    </div>
                    @endif
                            
                        </form>
                    </div>
                        <!-- <div class="row"> -->
                           
                           

                         <div class="col-lg-3 col-md-12">
                                <div class="grand-totall">
                                    <div class="title-wrap">
                                        <h4 class="cart-bottom-title section-bg-gary-cart">Cart Total</h4>
                                    </div>
                                    <h5>Sub Total<span id="total_price">₹{{$bill}}.00</span></h5>
                                    {{-- <div class="total-shipping">
                                        <h5>Total shipping</h5>
                                        <ul>
                                            <li><input type="checkbox"> Standard <span>₹20.00</span></li>
                                            <li><input type="checkbox"> Express <span>₹30.00</span></li>
                                        </ul>
                                    </div> --}}
                                    <h4 class="grand-totall-title">Grand Total <span id="grand_total">₹{{$bill}}.00</span></h4>
                                    <a href="<?php if(!empty(Auth::user()->id)){echo '/checkout/'.Auth::user()->id;} else{ echo '/login'; }?>">Proceed to Checkout</a>
                                </div>
                                 <div class="col-lg-12 col-md-12" style="float:right;">
                                <div class="cart-shiping-update-wrapper">
                                    <div class="cart-shiping-update">
                                        <a href="/home" style="border-radius:25px;">Continue Shopping</a>
                                    </div>
                                        {{-- <div class="cart-clear">
                                            <button>Update Shopping Cart</button>
                                            <a href="#">Clear Shopping Cart</a>
                                        </div> --}}
                                    </div>
                                {{-- <div class="cart-tax">
                                    <div class="title-wrap">
                                        <h4 class="cart-bottom-title section-bg-gray">Estimate Shipping And Tax</h4>
                                    </div>
                                    <div class="tax-wrapper">
                                        <p>Enter your destination to get a shipping estimate.</p>
                                        <div class="tax-select-wrapper">
                                            <div class="tax-select">
                                                <label>
                                                    * Country
                                                </label>
                                                <select class="email s-email s-wid">
                                                    <option>India</option>
                                                    <option>Nepal</option>
                                                    <option>Åland Islands</option>
                                                    <option>Afghanistan</option>
                                                    <option>Belgium</option>
                                                </select>
                                            </div>
                                            <div class="tax-select">
                                                <label>
                                                    * Region / State
                                                </label>
                                                <select class="email s-email s-wid">
                                                    <option>Delhi</option>
                                                    <option>Punjab</option>
                                                    <option>U.P</option>
                                                    <option>Bihar</option>
                                                    <option>Himachal Pradesh</option>
                                                </select>
                                            </div>
                                            <div class="tax-select">
                                                <label>
                                                    * Zip/Postal Code
                                                </label>
                                                <input type="text">
                                            </div>
                                            <button class="cart-btn-2" type="submit">Get A Quote</button>
                                        </div>
                                    </div>
                                </div> --}}
                            </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>



        @endsection


        @section('script')

        <script>


        // var count=<?php echo session()->get('count'); ?>;

        function deleteCartProduct(id){
            var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    // count--;

    $.ajax({
        /* the route pointing to the post function */
        url: '/cart/delete-product/'+id,
        type: 'POST',
        datatype: 'JSON',
        /* send the csrf-token and the input to the controller */
        data: {_token: CSRF_TOKEN, id: id},
        success: function (data) {
    $('#cart'+id).hide();
            $('#cartItem').html(data.cartItem);
            $("#total_price").empty();
            $("#total_price").append("₹" + data.bill);
            $("#grand_total").html("₹" + data.bill);
            if(data.bill <= 0){
              $("#checkoutLink").attr("href", "/");
              $("#checkoutLink").html('Continue Shopping');
          }
      }
  });
}


function decrement(id){
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            
            var action = 'minus' ;
            var quantity = $('#quantity'+id).val();
            if(quantity>1){
                
                $('#quantity'+id).val(--quantity);
                $.ajax({
                   url: '/update-cart',
                   type: 'POST',
                   data: {_token: CSRF_TOKEN, id: id, action: action},
                   success: function (data) {
               
               $("#total_price").empty();
               $("#total_price").append("₹" + data.bill);
               $("#grand_total").html("₹" + data.bill);
               $("#amount"+id).html("₹" + data.total);


           },
           failure: function (data) {
             alert(data.message);
         }
     });
            }
        }

        function increment(id){
        
            var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            
            var quantity = $('#quantity'+id).val();
            var action = 'plus' ;

            $('#quantity'+id).val(++quantity);
            $.ajax({
             url: '/update-cart',
             type: 'POST',
             data: {_token: CSRF_TOKEN, id: id, action:action},
             success: function (data) {
              
            $("#total_price").empty();
            $("#total_price").append("₹" + data.bill);
            $("#grand_total").html("₹" + data.bill);
            $("#amount"+id).html("₹" + data.total);

           },
           failure: function (data) {
               alert('Something went wrong');
           }
       });
   }

  
</script>

@endsection

resources/views/fyc-web/faq.blade.php
@extends('layouts.fyc')

@section('content')

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"></link>
<style type="text/css">
	#accordion { width: 100%; }
	[data-toggle="collapse"]:after {
display: inline-block;
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  content: "\f054";
  transform: rotate(90deg) ;
  transition: all linear 0.25s;
  float: right;
  }   
[data-toggle="collapse"].collapsed:after {
  transform: rotate(0deg) ;
}
</style>

<div class="breadcrumb-area bg-img" style="background-image:url(/fyc-new/images/bg/breadcrumb.jpg);">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <h2>FAQ page</h2>
                    <ul>
                        <li>
                            <a href="/homew">Home</a>
                        </li>
                        <li class="active">FAQ </li>
                    </ul>
                </div>
            </div>
        </div>

<div class="container mt-40 mb-40">
	<div class="row">
		<div id="accordion" role="tablist">
       @if($faq)
                                  @foreach($faq as $index => $faqData)
  <div class="card">
    <div class="card-header" role="tab" id="heading{{$index}}">
      <h5 class="mb-0">
        <a data-toggle="collapse" href="#collapse{{$index}}" aria-expanded="@if($index==0){{'true'}}@else{{'false'}}@endif " aria-controls="collapseOne">can i have multiple product at a time</a>
      </h5>
</div>

<div id="collapse{{$index}}" class="collapse @if($index==0){{'show'}}@endif" role="tabpanel" aria-labelledby="heading{{$index}}" data-parent="#accordion">
      <div class="card-body">
        Yes You can buy multiple prooduct at a time.
      </div>
</div>

</div>
@endforeach
@endif

</div>
</div>
		
	</div>
	
</div>

@endsection

resources/views/fyc-web/reply.blade.php
@extends('layouts/fyc')

@section('content')
<br><br>
      <main class="page-content">
        <div class="account-page-area">
          <div class="container">
            @if($helpSupport)
            <div class="row">
              <div class="col-12">
                <h3 class="contact-page-title text-center mb-2">Subject : {{$helpSupport->subject}}</h3>
                @if($replyMessages)
                @foreach($replyMessages as $reply)
                <div class="row justify-content-end">
                  <div class="col offset-md-8">
                    <br> 
                    <p class="d-block badge badge-pill {{$reply->reply_from == 'admin' ? 'float-left badge-success' : 'float-right badge-info'}}" style="font-size: 14px">{{$reply->message}}</p>
                  </div>
                </div>
                @endforeach

                @endif
                <br>
                <form method="post" action="{{ route('reply.store') }}">
                     {{ csrf_field() }}
                     <input type="text" name="token" value="{{$helpSupport->token}}" hidden>
                     <div class="form-group row justify-content-end">
                       <label for="message_content" class="col-sm-2 offset-md-6 col-form-label"></label>
                       <div class="col-sm-4">
                         <textarea rows="4" cols="40" class="form-control @error('message_content') is-invalid @enderror" name="message_content" id="message_content" placeholder="Your Query" required>{{old('message_content')}}</textarea>
                         @error('message_content')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                       </div>
                     </div>

                  <div class="form-group row float-right">
                    <div class="col ">
                      <button type="submit" class="btn btn-primary" style="background-color: #000033; border: none">Send</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            @else
              <h4 class="badge badge-pill badge-danger">Something Went Wrong</h4>
            @endif
          </div>
        </div>
      </main>
@endsection